---
apiVersion: v1
kind: Service
metadata:
  name: airflow-service
  labels:
    app: airflow
    environment: test
    revision: "1"
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: airflow
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: airflow
  labels:
    app: airflow
    environment: test
    revision: "1"
spec:
  port:
    targetPort: 8080
  to:
    kind: Service
    name: airflow-service
    weight: 100
  wildcardPolicy: None